// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String treinarRedePerceptron(
        {required List<bool> vetorMatriz1,
        required List<bool> vetorMatriz2,
        required List<bool> vetorTeste}) =>
    RustLib.instance.api.crateApiSimpleTreinarRedePerceptron(
        vetorMatriz1: vetorMatriz1,
        vetorMatriz2: vetorMatriz2,
        vetorTeste: vetorTeste);
